### ISSUE TITLE
Check for data.

### ISSUE THREAD

**Issue by raguay** [markwk/alfred-workflow-wordcounterapp#1]
You need this in the script for running periodically:

if yesterday not in data:
    print "Not used yesterday"
    exit()

If the program isn't running the data before ran, the original script will error. Adding these lines before using the data array will keep from producing an error. I run it in a Keyboard Maestro script that will display the output of the script as a notification if any.

**Comment by markwk** [comment]
Thanks @raguay Added a commit that hopefully fixes this. Please give it a look to see if I got it right. 

Out of curiosity any additional features you'd like to have on this project? I might do a few hours of more coding on it in a few weeks and would be open to suggestions. Feel free to post a new ticket or two.

**Comment by raguay** [comment]
That is right. That will keep it from crashing when the program isn't running the day before.
